services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=spring_jpa_memcached
    ports:
      - "5432:5432"
  memcached:
    image: memcached:1.6.19
    environment:
      - MEMCACHED_CACHE_SIZE=64
      - MEMCACHED_MAX_CONNECTIONS=1024
    ports:
      - "11211:11211"